// <auto-generated />
using System;
using AuditApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuditApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuditApp.Models.FormAutoElevadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AntideslizantesManoPisos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arrestallamas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AuditorId")
                        .HasColumnType("int");

                    b.Property<string>("AvisoRetroceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bocina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraAtrapamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraCinturon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraInfladoNeumaticos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraProhibicionCarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraProhibicionPersonas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraRiesgosBateriasYGas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraVelocidadCirculacionAut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraVelocidadCirculacionPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraVelocidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleraViasCirculacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckAvisoRetroceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckBocina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckCinturonSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckEspejos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckEstadoAsiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckExtintor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckFrenoPieMano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckLuces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckMandosServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckSistemaTransmision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CinturonSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuñasRuedas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementosProteccionGLP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElevadorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspejosRetrovisores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstructuraContraCaidas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtiquetaCargaMaxima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtiquetasCurvas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiquetastringerna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extintor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrenoEstacionario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRAM8412")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformeReparaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListadoControlRuedas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListadoFijacionBrazos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListadoFugasFluidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListadoNivelAceite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LucesGiroFreno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LucesTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualOperario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediosAsensoDesenso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperacionPersonalAut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramaMantenimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProteccionLLuvia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableDesvio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisionGeneralTriMestral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeguridadMandos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeñalizacionAltura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeñalizacionFueraServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SillaConductor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AutoElevadores");
                });

            modelBuilder.Entity("AuditApp.Models.FormHyM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditorId")
                        .HasColumnType("int");

                    b.Property<string>("BarreraOpticaEnclavamientoElectrico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarrosEmbalajes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionesInseguras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoblesPulsadores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entrenamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuinchesBalanceadores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HerramientasManuales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdHyM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iluminacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LimpiezaYorganizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParadaDeEmergencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerdidasAireAguaAceite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<string>("Protecciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuertasTablerosElectricos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableDesvio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HsyMs");
                });

            modelBuilder.Entity("AuditApp.Models.FormTableroElectrico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditorId")
                        .HasColumnType("int");

                    b.Property<string>("CarteleriaBuenEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleriaEPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteleriaSeñalizada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cerradura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPPCalzadoDielectrico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPPGuantesDielectrico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPPLentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MPCCandadosTarjetas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MPCProcEscritos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MPCTableroProtegido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matafuegos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdenLimpieza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsableDesvio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableroLibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableroYSector")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TablerosElectricos");
                });

            modelBuilder.Entity("AuditApp.Models.Planta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plantas");
                });

            modelBuilder.Entity("AuditApp.Models.UsuarioBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UsuarioBase");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("AuditApp.Models.Auditor", b =>
                {
                    b.HasBaseType("AuditApp.Models.UsuarioBase");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Auditor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AuditApp.Models.UsuarioBase", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AuditApp.Models.UsuarioBase", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditApp.Models.UsuarioBase", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AuditApp.Models.UsuarioBase", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
